# Generated by Django 6.0.7 on 2026-08-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_portresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
