# Generated by Django 6.0.7 on 2026-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scan_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='portresult',
            name='banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portresult',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
