# Generated by Django 6.0.7 on 2026-08-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_portresult_banner_portresult_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ssl_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='ssl_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='ssl_issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scan',
            name='tls_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
