# Generated by Django 6.0.7 on 2026-08-02 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scan_ssl_enabled_scan_ssl_expiry_scan_ssl_issuer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='scanner.scan')),
            ],
        ),
    ]
