# Generated by Django 6.0.7 on 2026-08-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_httpheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='scanner.scan')),
            ],
        ),
    ]
