# Generated by Django 6.0.7 on 2026-08-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_dnsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('cve_id', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=20)),
                ('cvss_score', models.FloatField()),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
