# Generated by Django 6.0.7 on 2026-08-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cvss_score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
