# Generated by Django 6.0.7 on 2026-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_alter_cve_cvss_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
